name: FontProof
description: A font design testing class for SILE
inputs:
  args:
    description: Arguments passed to fontproof; defaults to ‘-t test’.
    required: false
    default: -t test
runs:
  using: docker
  image: docker://ghcr.io/sile-typesetter/fontproof:v2.2.3
  entrypoint: sh
  args:
    - -c
    - fontproof ${{ inputs.args }}
branding:
  icon: book-open
  color: blue
