name: FontProof
description: A font design testing class for SILE
inputs:
  args:
    description: Arguments passed to sile
    required: false
    default: ""
runs:
  using: docker
  image: docker://ghcr.io/sile-typesetter/fontproof:v2.0.5
  args:
    - ${{ inputs.args }}
branding:
  icon: book-open
  color: blue
