#!/usr/bin/env sh
# SPDX-FileCopyrightText: © 2016 SIL International
# SPDX-License-Identifier: MIT

set -e

: "${SILETAG:=v0.15.10}"

REVISION=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')

RUNTIME_DEPS='words'

: "${DOCKER_BUILDKIT:=1}"
export DOCKER_BUILDKIT

docker build \
	--build-arg SILETAG="$SILETAG" \
	--build-arg REVISION="$REVISION" \
	--build-arg VERSION="${1:-$REVISION}" \
	--build-arg RUNTIME_DEPS="$RUNTIME_DEPS" \
	--tag ${DOCKER_REPO/-/}:$DOCKER_TAG \
	./
